### PR TITLE
Upgrade to Python 3.8 as minimal required version.

### PR DESCRIPTION
**Pull request by apollo13**
Python 3.7 is EOL and according to the readme only "active" python versions are supported. I think I found all occurrences of python 3.7 :)

### CODE REVIEW

**Comment by apollo13** [comment]
@microsoft-github-policy-service agree

**Comment by apollo13** [comment]
One thing that this PR does not do is update NOTICE.txt, seems as if zipp and colorama is no longer required according to pip-compile

**Review by karthiknadig — DISMISSED** [review]

**Review by karthiknadig — DISMISSED** [review]

**Comment by apollo13** [comment]
Okay, the windows tests are failing due to colorama not being in the generated requirements. Can someone with windows recreate those files? Personally I think the whole approach is flawed since the generated lock files are environment specific… In the worst case linux could require a library named X and windows a library named Y

**Comment by karthiknadig** [comment]
I will generate.

**Review by karthiknadig — APPROVED** [review]

**Review by karrtikr — APPROVED** [review]

**Pull request merged**
